openapi: 3.1.0
servers:
  - description: local
    url: http://localhost:8080
info:
  description: "moar (pronounce \"more\") is a modular augmentation registry for VueJS and ReactJS."
  title: moar
  version: v1.0.0