on: [push, pull_request]
name: Test
jobs:
  unit-test:
    strategy:
      matrix:
        # [1.15.x, 1.16.x]
        go-version: [1.21.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Install Go
        uses: actions/setup-go@master
        with:
          go-version: ${{ matrix.go-version }}
      - name: Unit tests
        run: go test -race ./...
  integration-tests:
    name: Integration tests
    strategy:
      matrix:
        # [1.15.x, 1.16.x]
        go-version: [ 1.21.x ]
        os: [ ubuntu-latest ]
    runs-on: ${{ matrix.os }}
    services:
      minio1:
        image: quay.io/minio/minio
        env:
          MINIO_ROOT_USER: minio
          MINIO_ROOT_PASSWORD: minio123
        ports:
          - 9000:9000
      # todo: we also need to add our local code changed service to be built...
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Go
        uses: actions/setup-go@master
      - name: Setup Node
        uses: actions/setup-node@master
      - name: Install bruno
        run: npm install -g @usebruno/cli
      - name: Run tests
        run: cd integration && bru run --env local