on: [push, pull_request]
name: Test
jobs:
  test:
    strategy:
      matrix:
        # [1.15.x, 1.16.x]
        go-version: [1.21.x]
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Test
        run: go test ./...
      - name: Integration test
        run: |
          curl --location --remote-name https://github.com/Orange-OpenSource/hurl/releases/download/$VERSION/hurl_4.2.0_amd64.deb
          sudo apt update && sudo apt install ./hurl_4.2.0_amd64.deb
          integration/run.sh